import { crayBoilPhoto, crayRawPhoto, reviewer_1, reviewer_2, reviewer_3 } from '../assets';
import { CraySize, CrayType } from './enums';

export const CRAYFISH = [
    {
        id: 1,
        weight: '10 - 20',
        size: '6 - 8',
        count: '50 - 100',
        price: 500,
        isAvailable: true,
        photo: crayBoilPhoto,
        craySize: CraySize.XS,
        crayType: CrayType.BOIL,
    },
    {
        id: 2,
        weight: '20 - 40',
        size: '8 - 12',
        count: '30 - 33',
        price: 600,
        isAvailable: false,
        photo: crayBoilPhoto,
        craySize: CraySize.S,
        crayType: CrayType.BOIL,
    },
    {
        id: 3,
        weight: '40 - 60',
        size: '12 - 15',
        count: '20 - 23',
        price: 700,
        isAvailable: true,
        photo: crayBoilPhoto,
        craySize: CraySize.M,
        crayType: CrayType.BOIL,
    },
    {
        id: 4,
        weight: '60 - 80',
        size: '15 - 17',
        count: '15 - 17',
        price: 800,
        isAvailable: true,
        photo: crayBoilPhoto,
        craySize: CraySize.L,
        crayType: CrayType.BOIL,
    },
    {
        id: 5,
        weight: '80 - 100',
        size: '17 - 20',
        count: '10 - 12',
        price: 800,
        isAvailable: true,
        photo: crayBoilPhoto,
        craySize: CraySize.XL,
        crayType: CrayType.BOIL,
    },
    {
        id: 6,
        weight: '100+',
        size: '20+',
        count: '10',
        price: 900,
        isAvailable: false,
        photo: crayBoilPhoto,
        craySize: CraySize.XXL,
        crayType: CrayType.BOIL,
    },
    {
        id: 7,
        weight: '10 - 20',
        size: '6 - 8',
        count: '50 - 100',
        price: 400,
        isAvailable: true,
        photo: crayRawPhoto,
        craySize: CraySize.XS,
        crayType: CrayType.RAW,
    },
    {
        id: 8,
        weight: '20 - 40',
        size: '8 - 12',
        count: '30 - 33',
        price: 500,
        isAvailable: true,
        photo: crayRawPhoto,
        craySize: CraySize.S,
        crayType: CrayType.RAW,
    },
    {
        id: 9,
        weight: '40 - 60',
        size: '12 - 15',
        count: '20 - 23',
        price: 600,
        isAvailable: false,
        photo: crayRawPhoto,
        craySize: CraySize.M,
        crayType: CrayType.RAW,
    },
    {
        id: 10,
        weight: '60 - 80',
        size: '15 - 17',
        count: '15 - 17',
        price: 700,
        isAvailable: false,
        photo: crayRawPhoto,
        craySize: CraySize.L,
        crayType: CrayType.RAW,
    },
    {
        id: 11,
        weight: '80 - 100',
        size: '17 - 20',
        count: '10 - 12',
        price: 800,
        isAvailable: true,
        photo: crayRawPhoto,
        craySize: CraySize.XL,
        crayType: CrayType.RAW,
    },
    {
        id: 12,
        weight: '100+',
        size: '20+',
        count: '10',
        price: 900,
        isAvailable: true,
        photo: crayRawPhoto,
        craySize: CraySize.XXL,
        crayType: CrayType.RAW,
    },
];

export const REVIEWS = [
    
    {
        id: 1,
        name: "Олена",
        comment: "Ви чудові! Дякую за настрій і неперевершений смак!",
        avatar: reviewer_2,
    },
    {
        id: 2,
        name: 'Володимир',
        comment: 'Все дуже смачно! Ви молодці',
        avatar: reviewer_1,
    },
    {
        id: 3,
        name: "Діана",
        comment: "Як завжди, найсмачніші в світі раки:) Обожнюю вас за якість:)",
        avatar: reviewer_3,
    },
];
